### ISSUE TITLE
Nukes dummy app

### ISSUE THREAD

**Issue by jacobq** [NullVoxPopuli/ember-addon-migrator#33]
Not that it's hard to manually restore and move the code over, but I was surprised that this lost the pages of my dummy app (e.g. [`tests/dummy/app/controllers/examples`](https://github.com/EmberMN/ember-cli-plotly/tree/jacobq/octane/tests/dummy/app/controllers/examples)). If this is the intended behavior, perhaps it'd be worth noting explicitly in the readme?

**Comment by NullVoxPopuli** [comment]
yeah -- it's a known issue (but thanks for reporting! it's good to have this!) -- it's not long term intended, because I think we want to prompt the user about what to do with the dummy app.

generally, there are two use cases:
 - augments tests
 - docs
 
when prompted, I think if the user choose docs, we'll want to create _another app_ but just for those docs, and copy the contents in there -- for test augmentation, we'd want to just copy -- which is probably the easier thing to do.
(I guess there is a third option, too -- do nothing -- tests are all self-contained)

**Comment by nicolechung** [comment]
Is this fixed now? I think with this PR: https://github.com/NullVoxPopuli/ember-addon-migrator/pull/84

And this PR: https://github.com/NullVoxPopuli/ember-addon-migrator/pull/81

**Comment by NullVoxPopuli** [comment]
yup! thanks!
