### ISSUE TITLE
Match embroider-build/addon-blueprint

### ISSUE THREAD

**Issue by ctjhoa** [NullVoxPopuli/ember-addon-migrator#36]
This addon should match https://github.com/embroider-build/addon-blueprint which seems the more advanced addon v2 blueprint

**Comment by NullVoxPopuli** [comment]
Agreed! I'll have something around Monday Tuesday to fix

**Comment by ctjhoa** [comment]
@NullVoxPopuli Any news on this?

**Comment by NullVoxPopuli** [comment]
Yeah, been working on it over here: https://github.com/NullVoxPopuli/ember-addon-migrator/pull/37

The last thing I need to do over there is 
 - fix all the tests
 - add a typescript transform since the `--typescript` flag isn't merged upstream yet
 
 and... I think that's it?
 hope to finish in the next week or so

**Comment by NullVoxPopuli** [comment]
I think this is done -- lemme know if anything is missing!
